[workspace]
members = [
    "utils/malvolio",
    "utils/prospero",
    "utils/mercutio",
    "utils/mercutio_codegen",
    "utils/portia",
    "main",
]
default-members = ["main"]

[profile.release]
lto = true
